theme: jekyll-theme-architect
title: Welcome to DJ's AI homepage! 
description: Feel free to bookmark this to keep an eye on my project updates, I will continue to add more information about the AI domain latest progress and innovation! 
